export const TipoNotificacao = {
  LEMBRETE_RESERVA_MEIO_PRAZO: "LEMBRETE_RESERVA_MEIO_PRAZO",
  LEMBRETE_RETIRADA_DIA: "LEMBRETE_RETIRADA_DIA",
  LEMBRETE_FECHAMENTO: "LEMBRETE_FECHAMENTO",
  INTENCAO_RETIRADA: "INTENCAO_RETIRADA",
  RECOLHIMENTO_PROXIMO: "RECOLHIMENTO_PROXIMO",
  DIVERGENCIA_RECOLHIMENTO: "DIVERGENCIA_RECOLHIMENTO",
} as const;

export type TipoNotificacao =
  (typeof TipoNotificacao)[keyof typeof TipoNotificacao];